Quanli_CuaHang_PTxemay/Quanli_CuaHang_PTxemay/Controllers/CartController.cs
using Quanli_CuaHang_PTxemay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Quanli_CuaHang_PTxemay.Controllers
{
    public class CartController : Controller
    {
        private const string CartSession = "CartSession";
        private const string CustomerSession = "CustomerSession";
        private const string BillSession = "BillSession";
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            double tongtien = 0;
            foreach (var item in list)
            {
                tongtien += (double)item.ProductID.GIABAN * item.Quantity;
            }
            ViewBag.tt = tongtien;
            return View(list);
        }
        public PHUTUNGXE ViewDetail(int id)
        {
            DataClasses1DataContext db = new DataClasses1DataContext();
            PHUTUNGXE a = new PHUTUNGXE();
            PHUTUNGXE x = db.PHUTUNGXEs.Where(s => s.MAPT == id).SingleOrDefault();
            a = x;
            return a;
        }
        public ActionResult AddnewItem( int id, int quantity)
        {
            var pro = ViewDetail(id);
            var cart = Session[CartSession];
            if(cart!=null)
            {
                var list = (List<CartItem>)cart;
                if(list.Exists(x=>x.ProductID.MAPT == id))
                {
                    foreach (var item in list)
                    {
                        if(item.ProductID.MAPT ==id)
                        {
                            item.Quantity += quantity;
                        }
                        
                    }
                }
                else
                {
                    var item = new CartItem();
                    item.ProductID= pro;
                    item.Quantity = quantity;
                    list.Add(item);
                }
                Session[CartSession] = list;
            }
            else
            {
                CartItem item = new CartItem();
                item.ProductID = pro;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);
                Session[CartSession] = list;
            }
            return RedirectToAction("Index", "Cart");

        }
        public JsonResult Update(string cartModel)
        {
            var jsoncart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var Sessioncart = (List<CartItem>)Session[CartSession];

            foreach(var item in Sessioncart)
            {
                var jsonitem = jsoncart.SingleOrDefault(x => x.ProductID.MAPT == item.ProductID.MAPT);
                if(jsonitem!=null)
                {
                    item.Quantity = jsonitem.Quantity;
                }
            }
            Session[CartSession] = Sessioncart;
            return Json(new
            {
                status = true
            });
        }
        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Delete(int id)
        {
            var Sessioncart = (List<CartItem>)Session[CartSession];
            Sessioncart.RemoveAll(x => x.ProductID.MAPT == id);
            Session[CartSession] = Sessioncart;
            return Json(new
            {
                status = true
            });
        }
       
        public JsonResult Delete_Favorite_list_item(int id)
        {
            DataClasses1DataContext db = new DataClasses1DataContext();
            var Sessionkh = (KHACHHANG)Session[CustomerSession];
            List<DANHSACHYEUTHICH> gh = new List<DANHSACHYEUTHICH>();
            gh = db.DANHSACHYEUTHICHes.Where(s => s.SDT == Sessionkh.SDT && s.MAPT == id).ToList();
            foreach(var item in gh)
            {
                var gh_item = item;
                db.DANHSACHYEUTHICHes.DeleteOnSubmit(gh_item);
                db.SubmitChanges();
            }    
            return Json(new
            {
                status = true
            });
        }    
        public KHACHHANG InforCus(string tel)
        {
            try
            {
                DataClasses1DataContext db = new DataClasses1DataContext();
                KHACHHANG k = new KHACHHANG();
                k = db.KHACHHANGs.FirstOrDefault(s => s.SDT == tel);
                if (k != null)
                    return k;
                else
                {
                    KHACHHANG newcustomer = new KHACHHANG();
                    newcustomer.SDT = tel;
                    db.KHACHHANGs.InsertOnSubmit(newcustomer);
                    db.SubmitChanges();
                    return newcustomer;
                }
            }
            catch
            {
                return null;
            }
             
        }
        public JsonResult LuuDanhsach(string tel)
        {
            if(tel!=null)
            {
                DataClasses1DataContext db = new DataClasses1DataContext();
                var Sessioncart = (List<CartItem>)Session[CartSession];
                Session[CustomerSession] = null;
                KHACHHANG customer = InforCus(tel);
                Session[CustomerSession] = customer;
                var cus = (KHACHHANG)Session[CustomerSession];
                foreach (var item in Sessioncart)
                {
                    DANHSACHYEUTHICH a = new DANHSACHYEUTHICH();
                    a.SDT = cus.SDT;
                    a.MAPT = item.ProductID.MAPT;
                    a.NGAYLAP = DateTime.Now;
                    a.SOLUONG_DS = item.Quantity;
                    db.DANHSACHYEUTHICHes.InsertOnSubmit(a);
                    db.SubmitChanges();
                }                
                HOADON newhd = new HOADON();
                newhd.SDT = cus.SDT;
                newhd.MANV = 1;
                newhd.NGAYBAN = DateTime.Now;
                newhd.TONGTIEN = 0;
                newhd.Tinhtrang = false;
                db.HOADONs.InsertOnSubmit(newhd);
                db.SubmitChanges();
                foreach(var item in Sessioncart)
                {
                    CTHD new_cthd = new CTHD();
                    new_cthd.MAHD = newhd.MAHD;
                    new_cthd.MAPT = item.ProductID.MAPT;
                    new_cthd.SOLUONG = item.Quantity;
                    new_cthd.DONGIA = item.ProductID.GIABAN;
                    new_cthd.THANHTIEN = item.ProductID.GIABAN * item.Quantity;
                    db.CTHDs.InsertOnSubmit(new_cthd);
                    db.SubmitChanges();
                    
                }    
                Session[CartSession] = null;
                return Json(new
                {
                    status = true
                });
            }
            return null;
        }      
        public ActionResult HienthiDanhsachyeuthich(string tel)
        {
            DataClasses1DataContext db = new DataClasses1DataContext();
            var Sessioncus = (KHACHHANG)Session[CustomerSession];
            if (Sessioncus == null)
            {
                if (tel != null)
                {
                    KHACHHANG kh = new KHACHHANG();
                    kh = db.KHACHHANGs.FirstOrDefault(s => s.SDT == tel);
                    if(kh==null)
                    {                       
                        return Json(new { status = false });
                    }
                    else
                    {
                        Sessioncus = kh;
                        List<DANHSACHYEUTHICH> gh = new List<DANHSACHYEUTHICH>();
                        gh = db.DANHSACHYEUTHICHes.Where(s => s.SDT == Sessioncus.SDT).ToList();
                        List<PHUTUNGXE> ptx = new List<PHUTUNGXE>();
                        foreach (var item in gh)
                        {
                            PHUTUNGXE a = new PHUTUNGXE();
                            a = db.PHUTUNGXEs.Where(s => s.MAPT == item.MAPT).FirstOrDefault();
                            ptx.Add(a);
                        }
                        ViewBag.kh = Sessioncus;
                        Session[CustomerSession] = kh;
                        ViewBag.danhsach = ptx.Distinct().ToList();
                        return Json(new { status = true });
                    }                        
                }
                return View();               
            }
            else
            {
                List<DANHSACHYEUTHICH> gh = new List<DANHSACHYEUTHICH>();
                gh = db.DANHSACHYEUTHICHes.Where(s => s.SDT == Sessioncus.SDT).ToList();
                List<PHUTUNGXE> ptx = new List<PHUTUNGXE>();
                foreach (var item in gh)
                {
                    PHUTUNGXE a = new PHUTUNGXE();
                    a = db.PHUTUNGXEs.Where(s => s.MAPT == item.MAPT).FirstOrDefault();
                    ptx.Add(a);
                }
                ViewBag.kh = Sessioncus;
                ViewBag.danhsach = ptx.Distinct().ToList();
                return View();
            }
                     
        }
        public ActionResult TinhTrang_DonHang(string tel)
        {
            DataClasses1DataContext db = new DataClasses1DataContext();
            KHACHHANG cus = (KHACHHANG)Session[CustomerSession];
            List<HOADON> lstHoadon = new List<HOADON>();
            if (cus == null)
            {
                if (tel != null)
                {
                    KHACHHANG kh = db.KHACHHANGs.FirstOrDefault(s => s.SDT == tel);
                    if (kh == null)
                        return Json(new { status = false });

Quanli_CuaHang_PTxemay/Quanli_CuaHang_PTxemay/Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quanli_CuaHang_PTxemay.Models;

namespace Quanli_CuaHang_PTxemay.Controllers
{
    public class SanphamController : Controller
    {
        // GET: Sanpham
        public ActionResult DOchoiXemay()
        {
            using (DataClasses1DataContext db = new DataClasses1DataContext())
            {
                List<PHUTUNGXE> dsQt = db.PHUTUNGXEs.Where(t => t.MALOAI.Equals(1)).ToList();
                return View(dsQt);

            }

        }

        public ActionResult Phutungthaythe()
        {
            using (DataClasses1DataContext db = new DataClasses1DataContext())
            {
                List<PHUTUNGXE> dsQt = db.PHUTUNGXEs.Where(t => t.MALOAI.Equals(2)).ToList();
                return View(dsQt);

            }

        }
        public ActionResult VoXemay()
        {
            using (DataClasses1DataContext db = new DataClasses1DataContext())
            {
                List<PHUTUNGXE> dsQt = db.PHUTUNGXEs.Where(t => t.MALOAI.Equals(3)).ToList();
                return View(dsQt);

            }

        }
        public ActionResult NhotXemay()
        {
            using (DataClasses1DataContext db = new DataClasses1DataContext())
            {
                List<PHUTUNGXE> dsQt = db.PHUTUNGXEs.Where(t => t.MALOAI.Equals(4)).ToList();
                return View(dsQt);

            }

        }
        public ActionResult PhuKien()
        {
            using (DataClasses1DataContext db = new DataClasses1DataContext())
            {
                List<PHUTUNGXE> dsQt = db.PHUTUNGXEs.Where(t => t.MALOAI.Equals(5)).ToList();
                return View(dsQt);

            }

        }
        public ActionResult Dokieng()
        {
            using (DataClasses1DataContext db = new DataClasses1DataContext())
            {
                List<PHUTUNGXE> dsQt = db.PHUTUNGXEs.Where(t => t.MALOAI.Equals(2)).ToList();
                return View(dsQt);

            }

        }
        public ActionResult ChitietSp(int masp)
        {
            DataClasses1DataContext db = new DataClasses1DataContext();
            PHUTUNGXE ptx = db.PHUTUNGXEs.SingleOrDefault(n => n.MAPT == masp);
            if (ptx == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<PHUTUNGXE> x = db.PHUTUNGXEs.Where(t => t.MALOAI == ptx.MALOAI).Take(6).ToList();
            ViewBag.ptungloai = x;
            return View(ptx);
        }
    }
}

Quanli_CuaHang_PTxemay/Quanli_CuaHang_PTxemay/Views/Cart/ChitietDonHang.cshtml
@using Quanli_CuaHang_PTxemay.Models;
@model List<CTHD>
@{
    ViewBag.Title = "ChitietDonHang";
    Layout = "~/Views/Shared/_LayoutPage4.cshtml";
}
<table class="table">
    <thead>
        <tr>
            <td style="font-weight:700">Mã HD</td>
            <td style="font-weight:700">Tên Sản phẩm</td>
            <td style="font-weight:700">Hình ảnh</td>
            <td style="width: 117px;font-weight:700">Số lượng</td>
            <td style="font-weight:700">Đơn giả</td>
            <td style="font-weight:700">Thành tiền</td>
            <td style="font-weight:700"></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.MAHD</td>
                <td>@item.PHUTUNGXE.TENPT</td>
                <td><img width="100" src="~/Assert/Hinh_Anh_PTX_DA/@item.PHUTUNGXE.HINH" /></td>
                <td><input type="text" class="txtquantity" data-id="@item.PHUTUNGXE.MAPT" value="@item.SOLUONG" /></td>
                <td>@String.Format("{0:#,##}", Convert.ToInt32(item.PHUTUNGXE.GIABAN.GetValueOrDefault(0)))đ</td>
                <td>@String.Format("{0:#,##}", Convert.ToInt32(((item.PHUTUNGXE.GIABAN.GetValueOrDefault(0) * item.SOLUONG))))đ</td>
            </tr>
        }       
    </tbody>
</table>

Quanli_CuaHang_PTxemay/Quanli_CuaHang_PTxemay/Views/Cart/HienthiDanhsachyeuthich.cshtml
@using Quanli_CuaHang_PTxemay.Models;

@{
    ViewBag.Title = "HienthiDanhsachyeuthich";
    Layout = "~/Views/Shared/_LayoutPage4.cshtml";
}
@if (ViewBag.kh == null)
{
    <div style="margin-top:10px;color: #d42a2a;">
        <h5><i style="margin-right: 10px;" class="fa fa-bullhorn" aria-hidden="true"></i>Hãy nhập số điện thoại của bạn</h5>
        <input style=" height: 38px; padding: 0; font-size: 15px; width: 232px; padding-left: 20px;" type="tel" id="tel-number" placeholder="Nhập số điện thoại của bạn" />
        <button style="border: 1px solid;font-weight:700" id="btnGui" class="btn">Tìm kiếm</button>
    </div>
}
else
{

    if (ViewBag.danhsach == null)
    {
        <p class="alert alert-danger">Bạn chưa có sản phẩm yêu thích </p>
    }
    else
    {

        <table class="table">
            <thead>
                <tr>
                    <td>Mã</td>
                    <td style="width:200px;">Tên Sản Phẩm</td>
                    <td>Hình ảnh</td>
                    <td>Đơn vị tính</td>
                    <td>Giá Bán</td>
                    <td></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (PHUTUNGXE item in ViewBag.danhsach)
                {
                <tr>
                    <td>@item.MAPT</td>
                    <td>@item.TENPT</td>
                    <td><img style="width:100px;" src="~/Assert/Hinh_Anh_PTX_DA/@item.HINH"/></td>
                    <td>@item.DVT</td>
                    <td>@item.GIABAN</td>
                    <td><a style=" margin-top: -7px;" href="@Url.Action("ChitietSp","Sanpham", new {masp = item.MAPT})" class="btn btn-primary">Xem chi tiết</a></td>
                    <td><span><a href="#" data-id="@item.MAPT" class="btn-delete"><i style="color:red;" class="fa fa-trash" aria-hidden="true"></i></a></span></td>
                </tr>
                
            }


                </tbody>
            </table>

        }
    }
<script>
    var cart = {
        init: function () {
            cart.regEvents();
        },
        regEvents: function () {
            $('#btnGui').off('click').on('click', function () {
                var mobile_check = /^[0-9]{10}$/;
                var telnumber_check = $('#tel-number').val();
                if (mobile_check.test(telnumber_check)) {
                    var telnumber = $('#tel-number').val();
                }
                else {
                    alert('Số điện thoại của bạn không đúng định dạng')
                }

                $.ajax({
                    url: '/cart/hienthidanhsachyeuthich',
                    data: { tel: telnumber },
                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/cart/hienthidanhsachyeuthich";
                        }
                        else {
                            alert("Số điện thoại của bạn chưa có trong hệ thống");
                            window.location.href = "/cart/hienthidanhsachyeuthich";
                        }
                    }
                });
            });
            $('.btn-delete').off('click').on('click', function (e) {
                e.preventDefault()
                $.ajax({
                    data: { id: $(this).data('id') },
                    url: '/cart/delete_favorite_list_item',
                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/cart/hienthidanhsachyeuthich";
                        }
                    }
                });
            });
        }
    }
    cart.init();
</script>

Quanli_CuaHang_PTxemay/Quanli_CuaHang_PTxemay/Views/Cart/Index.cshtml
@using Quanli_CuaHang_PTxemay.Models;
@model List<CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage4.cshtml";
}

@if (Model.Count > 0)
{
    <h5 style="width:40%;border-bottom:5px solid;color:orange;margin-top:10px;">Danh sách sản phẩm mà bạn đã chọn:</h5>
    <table class="table">
        <thead>
            <tr>
                <td style="font-weight:700">Mã</td>
                <td style="font-weight:700">Tên Sản phẩm</td>
                <td style="font-weight:700">Hình ảnh</td>
                <td style="width: 117px;font-weight:700">Số lượng</td>
                <td style="font-weight:700">Đơn giả</td>
                <td style="font-weight:700">Thành tiền</td>
                <td style="font-weight:700"></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ProductID.MAPT</td>
                    <td>@item.ProductID.TENPT</td>
                    <td><img width="100" src="~/Assert/Hinh_Anh_PTX_DA/@item.ProductID.HINH" /></td>
                    <td><input type="text" class="txtquantity" data-id="@item.ProductID.MAPT" value="@item.Quantity" /></td>
                    <td>@String.Format("{0:#,##}", Convert.ToInt32(item.ProductID.GIABAN.GetValueOrDefault(0)))đ</td>
                    <td>@String.Format("{0:#,##}", Convert.ToInt32(((item.ProductID.GIABAN.GetValueOrDefault(0) * item.Quantity))))đ</td>
                    <td><span><a href="#" data-id="@item.ProductID.MAPT" class="btn-delete"><i style="color:red;" class="fa fa-trash" aria-hidden="true"></i></a></span></td>
                </tr>
            }
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><h6 style=" font-size: 16px; margin-top: 4px;color:red">TỔNG TIỀN:</h6></td>
            <td> <p style="color:orangered;font-size:20px;font-weight:700">@String.Format("{0:#,##}", Convert.ToInt32(ViewBag.tt))đ</p></td>
        </tr>
        </tbody>
    </table>
    <button style="margin-right:50px;border:1px solid;font-weight:700" id="btnContinue" class="btn">Chọn sản phẩm khác</button>
    <button style="margin-right:50px;border:1px solid;font-weight:700" id="btnUpdate" class="btn">Cập nhật danh sách</button>
    <button style="margin-right:50px;border:1px solid;font-weight:700" id="btnDeleteAll" class="btn">Xóa danh sách</button>
    <input style=" height: 38px; padding: 0; font-size: 15px; width: 232px; padding-left: 20px;" type="tel" class="tel-number" placeholder="Nhập số điện thoại của bạn" /><button style="border: 1px solid;font-weight:700" id="btnLuu" class="btn">Đặt Hàng</button>
   
    <script>
        var cart = {
            init: function () {
                cart.regEvents();
            },
            regEvents: function () {
                $('#btnContinue').off('click').on('click', function () {
                    window.location.href = "/trangchu/index";
                });
                $('#btnUpdate').off('click').on('click', function () {
                    var listProduct = $('.txtquantity');
                    var cartList = [];
                    $.each(listProduct, function (i, item) {
                        cartList.push({
                            Quantity: $(item).val(),
                            ProductID: {
                                MAPT: $(item).data('id') 
                            }
                        });
                    });
                    $.ajax({
                        url: '/cart/update',
                        data: { cartModel: JSON.stringify(cartList) },
                        dataType: 'json',
                        type: 'POST',
                        success: function (res) {
                            if (res.status == true) {
                                window.location.href = "/cart/index";
                            }
                        }
                    });
                });
                $('#btnDeleteAll').off('click').on('click', function () {                    
                    $.ajax({
                        url: '/cart/deleteall',                        
                        dataType: 'json',
                        type: 'POST',
                        success: function (res) {
                            if (res.status == true) {
                                window.location.href = "/cart/index";
                            }
                        }
                    });
                });
                $('.btn-delete').off('click').on('click', function (e) {
                    e.preventDefault()
                    $.ajax({
                        data: { id: $(this).data('id') },
                        url: '/cart/delete',
                        dataType: 'json',
                        type: 'POST',
                        success: function (res) {
                            if (res.status == true) {
                                window.location.href = "/cart/index";
                            }
                        }
                    });
                });
                $('#btnLuu').off('click').on('click', function () {
                    var mobile_check = /^[0-9]{10}$/;
                    var telnumber_check = $('.tel-number').val();
                    if (mobile_check.test(telnumber_check)) {
                        if (confirm('Bạn có muốn tiếp tục lưu việc này sẽ xóa đi danh sách hiện tại')) {
                            var telnumber = $('.tel-number').val();
                        }
                        else {

                        }
                       
                    }
                    else {
                        alert('Số điện thoại của bạn không đúng định dạng')
                    }
                                                     
                    $.ajax({
                        url: '/cart/luudanhsach',
                        data: { tel: telnumber },
                        dataType: 'json',
                        type: 'POST',
                        success: function (res) {
                            if (res.status == true) {
                                window.location.href = "/cart/tinhtrang_donHang";
                            }
                        }
                    });
                });
            }
        }
        cart.init();
    </script>
}
else
{
    <span style="position:absolute" class="alert alert-danger">Bạn chưa có sản phẩm nào được chọn</span>
}

Quanli_CuaHang_PTxemay/Quanli_CuaHang_PTxemay/Views/Cart/TinhTrang_DonHang.cshtml
@using Quanli_CuaHang_PTxemay.Models;

@{
    ViewBag.Title = "TinhTrang_DonHang";
    Layout = "~/Views/Shared/_LayoutPage4.cshtml";
}
@if (ViewBag.kh == null)
{
    <div style="margin-top:10px;color: #d42a2a;">
        <h5><i style="margin-right: 10px;" class="fa fa-bullhorn" aria-hidden="true"></i>Hãy nhập số điện thoại của bạn</h5>
        <input style=" height: 38px; padding: 0; font-size: 15px; width: 232px; padding-left: 20px;" type="tel" id="tel-number" placeholder="Nhập số điện thoại của bạn" />
        <button style="border: 1px solid;font-weight:700" id="btnGui" class="btn">Tìm kiếm</button>
    </div>
}
else
{
    if (ViewBag.dshd.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <td>Mã HD</td>
                    <td>Số điện thoại</td>
                    <td>Ngày Bán</td>
                    <td>Tổng Tiền</td>
                    <td>Tình trạng</td>
                    <td></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.dshd)
                {
                <tr>
                    <td>@item.MAHD</td>
                    <td>@item.SDT</td>
                    <td>@item.NGAYBAN</td>

                    <td>@String.Format("{0:#,##}", Convert.ToInt32(item.TONGTIEN))đ</td>
                    @if (item.Tinhtrang == false)
                    {
                        <td>Đang duyệt đơn hàng</td>
                        <td><a style="margin-top: -8px;" href="@Url.Action("ChitietDonHang", "Cart", new { idHD = item.MAHD })" class="btn btnXemchitiet">Xem chi tiết</a></td>
                        <td><button style="margin-top: -8px;" data-id="@item.MAHD" class="btn btnXoaDonHang">Xóa Đơn Hàng</button></td>
                    }
                    else
                    {
                        <td><i style="margin-right:10px;" class="fa fa-bicycle" aria-hidden="true"></i>Đang giao Hàng</td>
                        <td><a style="margin-top: -8px;" href="@Url.Action("ChitietDonHang", "Cart", new { idHD = item.MAHD })" class="btn btnXemchitiet">Xem chi tiết</a></td>
                    }


                </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <span style="position:absolute" class="alert alert-danger">Bạn chưa có hóa đơn nào !</span>
    }
}
<script>
    var cart = {
        init: function () {
            cart.regEvents();
        },
        regEvents: function () {
            $('.btnXoaDonHang').off('click').on('click', function (e) {
                $.ajax({
                    data: { idHD: $(this).data('id') },
                    url: '/cart/delete_giohang',
                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/cart/tinhtrang_donHang";
                        }
                    }
                });
            });
            $('#btnGui').off('click').on('click', function () {
                var mobile_check = /^[0-9]{10}$/;
                var telnumber_check = $('#tel-number').val();
                if (mobile_check.test(telnumber_check)) {
                    var telnumber = $('#tel-number').val();
                }
                else {
                    alert('Số điện thoại của bạn không đúng định dạng')
                }

                $.ajax({
                    url: '/cart/hienthidanhsachyeuthich',
                    data: { tel: telnumber },
                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            window.location.href = "/cart/tinhtrang_donhang";
                        }
                        else {
                            alert("Số điện thoại của bạn chưa có trong hệ thống");
                            window.location.href = "/cart/tinhtrang_donhang";
                        }
                    }
                });
            });

        }
    }
    cart.init();
</script>